---
title: "Estudantes"
author: "M. Saraiva"
date: '2022-07-01'
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(data.table)
library(sf)
library(viridis)
library(ggspatial)
```

## Análise Exploratória - Alunos


## Carregar dados

```{r cars}
alunos_df <- read_rds("../../../data/alunos.rds")
```

## Alunos

```{r}
alunos_df
```

Alunos de ensino fundamental

```{r}
alunos_df %>%
  mutate(SG_ETAPA = str_remove(SG_ETAPA, " ESPECIAL")) %>%
  count(SG_ETAPA, SG_SERIE_ENSINO) %>%
  filter(SG_ETAPA == "FUNDAMENTAL")
```

Alunos de ensino infantil

```{r}
alunos_df %>%
  mutate(SG_ETAPA = str_remove(SG_ETAPA, " ESPECIAL")) %>%
  count(SG_ETAPA, SG_SERIE_ENSINO) %>%
  filter(SG_ETAPA == "INFANTIL")

```
Alunos do ensino infantil unificado


```{r}
alunos_df %>%
  mutate(SG_ETAPA = str_remove(SG_ETAPA, " ESPECIAL"),
         ano_nascimento = lubridate::year(DT_NASCIMENTO_ALUNO)) %>%
  count(SG_ETAPA, SG_SERIE_ENSINO, ano_nascimento) %>%
  filter(SG_ETAPA == "INFANTIL", n > 100)

```


```{r}
alunos_df %>%
  count(TP_RACA_COR, DC_RACA_COR)
```

```{r}
alunos_df %>%
  count(BF, FAIXA_RENDA) %>%
  replace_na(list(BF = "NAO")) %>%
  pivot_wider(names_from = BF, values_from = n)
```

,[QT_DISTANCIA]	DISTANCIA À PE PARA ESCOLA DA MATRICULA
,[QT_DISTANCIA_CARRO]	DISTANCIA DE CARRO PARA ESCOLA DA MATRICULA
,[TEG]	SE UTILIZA TRANSPORTE NA MATRICULA

```{r}
alunos_df %>%
  select(CD_ALUNO, QT_DISTANCIA, QT_DISTANCIA_CARRO, TEG) %>%
  mutate(QT_DISTANCIA = as.numeric(QT_DISTANCIA)) %>%
  filter(QT_DISTANCIA < 2000) %>%
  ggplot() +
  geom_histogram(aes(QT_DISTANCIA)) 
  # scale_x_log10() +
  # facet_wrap(~TEG)
```
```{r}
alunos_df %>%
  select(CD_ALUNO, SG_SERIE_ENSINO, QT_DISTANCIA, QT_DISTANCIA_CARRO, TEG) %>%
  mutate(QT_DISTANCIA = as.numeric(QT_DISTANCIA)) %>%
  filter(QT_DISTANCIA < 2000) %>%
  ggplot() +
  geom_histogram(aes(QT_DISTANCIA)) +
  facet_wrap(~SG_SERIE_ENSINO)
```


```{r}
alunos_df %>%
  count(TEG)
```


```{r}
alunos_geo_df <- alunos_geo_df %>% drop_na()
alunos_sf <- alunos_geo_df %>% st_as_sf(coords = c("lon", "lat"), crs = 4326)
alunos_geo_df$hex <- h3jsr::point_to_h3(alunos_sf, res = 8)

hex_alunos <- alunos_geo_df %>% group_by(hex) %>% summarise(n = n())
hex_alunos$geometry <- h3jsr::h3_to_polygon(hex_alunos$hex)
hex_alunos <- st_as_sf(hex_alunos, crs = 4326)
```



```{r}
hex_alunos %>%
  filter(n > 8) %>%
  ggplot() +
  annotation_map_tile(type = "cartolight", zoom = 10, progress = "none") +
  geom_sf(aes(fill=n), color = NA) +
  scale_fill_viridis()
```






